# Generated by Django 5.2.5 on 2025-08-13 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.profile')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'بالا'), (2, 'متوسط'), (3, 'پایین')], default=2)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='accounts.profile')),
                ('tags', models.ManyToManyField(blank=True, related_name='todos', to='todos.tag')),
            ],
            options={
                'ordering': ('is_done', 'priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='todo_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todos.todo')),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['profile', 'name'], name='todos_tag_profile_65f617_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('profile', 'name')},
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['profile', 'is_done', 'archived'], name='todos_todo_profile_9e29ae_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['due_date'], name='todos_todo_due_dat_f2739d_idx'),
        ),
    ]
